services:
  mkdocs:
    container_name: mkdocs_material
    image: jferjan/mkdocs-material:1
    #image: squidfunk/mkdocs-material:9.1.21
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      TZ: "Europe/Ljubljana"
    volumes:
      - .:/docs
    command: 
      - serve
      - "--dev-addr=0.0.0.0:8000"