site_name: jaka.ferjan.net
site_url: https://jaka.ferjan.net/

nav:
    - Naslovnica: index.md
    - Zapisi: zapisi.md

theme:
  name: material
  language: sl
  font: false
  features:  
    - navigation.tabs # horizontalna navigacija
    # - navigation.tabs.sticky  
    - navigation.top # back to top - neprevedeno v slo
    - search.suggest
    - search.highlight
  logo: img/JF_logo_white_on_transparent.png
  favicon: img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Preklopi na temni način
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Preklopi na svetli način

extra_javascript:
  # Add meta noindex
  - js/noindex.js

markdown_extensions:

  # Python Markdown
  - abbr # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/buttons/
  - def_list # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - footnotes # https://squidfunk.github.io/mkdocs-material/reference/footnotes/#adding-footnote-references
  - md_in_html # https://squidfunk.github.io/mkdocs-material/reference/images/
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.highlight:
      #anchor_linenums: true
      #linenums: true
  - pymdownx.inlinehilite # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-inline-code-blocks
  - pymdownx.snippets
  - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/formatting/#adding-keyboard-keys
  #- pymdownx.mark
  #- pymdownx.smartsymbols
  - pymdownx.superfences
  #- pymdownx.tabbed:
  #    alternate_style: true
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists
      custom_checkbox: true
  - pymdownx.tilde # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde

plugins:
  - tags:
      tags_file: zapisi.md
  - search:
     lang: sl

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ferjan/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@JakaFerjan
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@fotrjaka
    - icon: fontawesome/brands/github 
      link: https://github.com/jferjan
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/jferjan
    - icon: material/bike-fast
      link: https://www.komoot.com/user/812042217858

copyright: Copyright &copy; Jaka Ferjan